export const CoinsJson: [string, string][] = [
  ['AFEGANISTÃO	Afghani - AFN', 'AFN'],
  ['ALBANIA	Lek - ALL', 'ALL'],
  ['ALEMANHA	Euro - EUR', 'EUR'],
  ['ANDORRA	Euro - EUR', 'EUR'],
  ['ANGOLA	Kwanza - AOA', 'AOA'],
  ['ANGUILA	Dólar do Caribe Oriental - XCD', 'XCD'],
  ['Nenhum ', ''],
  ['ANTÍGUA E BARBUDA	Dólar do Caribe Oriental - XCD', 'XCD'],
  ['ARÁBIA SAUDITA	Rial saudita - SAR', 'SAR'],
  ['ARGÉLIA	Dinar argelino - DZD', 'DZD'],
  ['ARGENTINA	Peso argentino - ARS', 'ARS'],
  ['ARMÊNIA	Dram armênio - AMD', 'AMD'],
  ['ARUBA	Florim arubano - AWG', 'AWG'],
  ['AUSTRÁLIA	Dólar australiano - AUD', 'AUD'],
  ['ÁUSTRIA	Euro - EUR', 'EUR'],
  ['AZERBAIJÃO	Manat azerbaijano - AZN', 'AZN'],
  ['BAHAMAS	Dólar das Bahamas - BSD', 'BSD'],
  ['BAHREIN	Dinar bareinita - BHD', 'BHD'],
  ['BANGLADESH	Taka - BDT', 'BDT'],
  ['BARBADOS	Dólar barbadense - BBD', 'BBD'],
  ['BAREIN	Dinar bareinita - BHD', 'BHD'],
  ['BÉLGICA	Euro - EUR', 'EUR'],
  ['BELIZE	Dólar de Belize - BZD', 'BZD'],
  ['BENIN	Francos CFA - XOF', 'XOF'],
  ['BERMUDAS	Dólar das Bermudas - BMD', 'BMD'],
  ['BOLÍVIA	Boliviano - BOB', 'BOB'],
  ['BÓSNIA E HERZEGOVINA	Convite - BAM', 'BAM'],
  ['BOTSUANA	Pula - BWP', 'BWP'],
  ['BRASIL	Real - BRL', 'BRL'],
  ['BRUNEI	Dólar de Brunei - BND', 'BND'],
  ['BULGÁRIA	Lev - BGN', 'BGN'],
  ['BURKINA FASO	Francos CFA - XOF', 'XOF'],
  ['BURUNDI	Francos CFA - XOF', 'XOF'],
  ['BUTÃO	Ngultrum - BTN', 'BTN'],
  ['CABO VERDE	Escudo cabo-verdiano - CVE', 'CVE'],
  ['CAMARÕES	Francos CFA - XAF', 'XAF'],
  ['CAMBOJA	Riel - KHR', 'KHR'],
  ['CANADÁ	Dólar canadense - CAD', 'CAD'],
  ['CATAR	Rial catariano - QAR', 'QAR'],
  ['CAZAQUISTÃO	Tenge - KZT', 'KZT'],
  ['CHADE	Francos CFA - XAF', 'XAF'],
  ['CHILE	Peso chileno - CLP', 'CLP'],
  ['CHINA	Yuan - CNY', 'CNY'],
  ['CHIPRE	Euro - EUR', 'EUR'],
  ['COLÔMBIA	Peso colombiano - COP', 'COP'],
  ['COMORES	Francos CFA - XAF', 'XAF'],
  ['CONGO	Francos CFA - XAF', 'XAF'],
  ['COREIA DO NORTE	Won - KPW', 'KPW'],
  ['COREIA DO SUL	Won - KRW', 'KRW'],
  ['COSTA DO MARFIM	Francos CFA - XOF', 'XOF'],
  ['COSTA RICA	Colón - CRC', 'CRC'],
  ['CROÁCIA	Kuna - HRK', 'HRK'],
  ['CUBA	Peso cubano - CUP', 'CUP'],
  ['DINAMARCA	Coroa dinamarquesa - DKK', 'DKK'],
  ['DJIBUTI	Francos CFA - XAF', 'XAF'],
  ['DOMINICA	Dólar das Bahamas - BSD', 'BSD'],
  ['EGITO	Pound egípcio - EGP', 'EGP'],
  ['EL SALVADOR	Colón - SVC', 'SVC'],
  ['EMIRADOS ÁRABES UNIDOS	Dirham dos Emirados Árabes Unidos - AED', 'AED'],
  ['EQUADOR	Sucre - ECS', 'ECS'],
  ['ERITRÉIA	Nakfa - ERN', 'ERN'],
  ['ESLOVÁQUIA	Coroa eslovaca - SKK', 'SKK'],
  ['ESLOVÊNIA	Tolar - SIT', 'SIT'],
  ['ESPANHA	Euro - EUR', 'EUR'],
  ['ESTADOS UNIDOS	Dólar americano - USD', 'USD'],
  ['ESTÔNIA	Coroa estoniana - EEK', 'EEK'],
  ['ETIÓPIA	Birr - ETB', 'ETB'],
  ['FIJI	Dólar de Fiji - FJD', 'FJD'],
  ['FILIPINAS	Peso filipino - PHP', 'PHP'],
  ['FINLÂNDIA	Euro - EUR', 'EUR'],
  ['FRANÇA	Euro - EUR', 'EUR'],
  ['GABÃO	Francos CFA - XAF', 'XAF'],
  ['GÂMBIA	Dalasi - GMD', 'GMD'],
  ['GANA	Cedi - GHS', 'GHS'],
  ['GEÓRGIA	Lari - GEL', 'GEL'],
  ['GRÉCIA	Euro - EUR', 'EUR'],
  ['GRONELÂNDIA	Dólar das Bermudas - BMD', 'BMD'],
  ['GUADALUPE	Dólar das Bermudas - BMD', 'BMD'],
  ['GUAM	Dólar das Bermudas - BMD', 'BMD'],
  ['GUATEMALA	Quetzal - GTQ', 'GTQ'],
  ['GUERNSEY	Dólar das Bermudas - BMD', 'BMD'],
  ['GUIANA	Dólar das Bermudas - BMD', 'BMD'],
  ['GUIANA FRANCESA	Euro - EUR', 'EUR'],
  ['GUINÉ	Euro - EUR', 'EUR'],
  ['GUINÉ EQUATORIAL	Euro - EUR', 'EUR'],
  ['GUINÉ-BISSAU	Euro - EUR', 'EUR'],
  ['HAITI	Gourde - HTG', 'HTG'],
  ['HONDURAS	Lempira - HNL', 'HNL'],
  ['HONG KONG	Dólar de Hong Kong - HKD', 'HKD'],
  ['HUNGRIA	Forint - HUF', 'HUF'],
  ['IÊMEN	Rial iemenita - YER', 'YER'],
  ['ILHA BOUVET	Euro - EUR', 'EUR']
];
